baseURL: https://cienciacomdados.netlify.app
title: CiÃªncia com Dados
theme: airspace-hugo
paginate: '4'
summaryLength: '30'
disqusShortname: ''
disableLanguages: [en]
defaultContentLanguage: pt
outputs:
  home: HTML
markup:
  goldmark:
    renderer:
      unsafe: yes
params:
  author: acsjunior
  contact_form_action: https://formspree.io/f/xbjpnaew
  cookies:
    enable: yes
    expire_days: 2
  description: This is meta description
  email: junior@cienciacomdados.com.br
  gmap:
    enable: yes
    gmap_api: AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU
    map_latitude: '-25.4950501'
    map_longitude: '-49.4298835'
    map_marker: images/marker.png
  google_analitycs_id: ''
  location: Curitiba, PR - Brasil
  logo: images/logo.png
  logo_width: 150px
  # mobile: 0124857985320
  multi_author: no
  nav_button:
    enable: yes
    label: Get A Quote
    link: contact
  plugins:
    css:
      - attributes: media='screen'
        link: plugins/bootstrap/bootstrap.min.css
      - attributes: ''
        link: plugins/Ionicons/css/ionicons.min.css
      - attributes: ''
        link: plugins/magnific-popup/magnific-popup.min.css
      - attributes: ''
        link: plugins/slick/slick.css
    js:
      - attributes: ''
        link: plugins/jQuery/jquery.min.js
      - attributes: ''
        link: plugins/bootstrap/bootstrap.min.js
      - attributes: ''
        link: plugins/slick/slick.min.js
      - attributes: ''
        link: plugins/magnific-popup/magnific-popup.min.js
      - attributes: ''
        link: plugins/shuffle/shuffle.min.js
      - attributes: defer
        link: plugins/google-map/gmap.js
  preloader:
    enable: yes
    preloader: ''
  social:
    - icon: ion-social-youtube-outline
      link: '#'
    - icon: ion-social-linkedin-outline
      link: '#'
    #- icon: ion-social-pinterest-outline
    #  link: '#'
    - icon: ion-social-github-outline
      link: '#'
    - icon: ion-social-twitter-outline
      link: '#'
    - icon: ion-social-facebook-outline
      link: '#'
  widgets:
    sidebar:
      - recent_posts
      - taxonomy_category
      - taxonomy_tags
Languages:
  pt:
    contentDir: content/portuguese
    copyright: Copyright &copy; 2020 [Themefisher](https://themefisher.com) All Rights
      Reserved
    languageCode: pt-br
    languageName: Pt
    menu:
      footer:
        - URL: about
          name: Sobre
          weight: 1
        #- URL: project
        #  name: Project
        #  weight: 2
        #- URL: service
        #  name: Service
        #  weight: 3
        #- URL: pricing
        #  name: Pricing
        #  weight: 4
        #- URL: faq
        #  name: FAQ
        #  weight: 5
        - URL: contact
          name: Contato
          weight: 6
      main:
        - URL: /
          name: Home
          weight: 1
        - URL: about
          name: Sobre
          weight: 2
        #- URL: project
        #  name: Project
        #  weight: 3
        - URL: blog
          name: Blog
          weight: 4
        #- hasChildren: yes
        #  name: Pages
        #  weight: 5
        #- URL: faq
        #  name: FAQ
        #  parent: Pages
        #- URL: pricing
        #  name: Pricing
        #  parent: Pages
        #- URL: service
        #  name: Service
        #  parent: Pages
        - URL: contact
          name: Contato
          weight: 6
    weight: 1
  en:
    contentDir: content/english
    copyright: Copyright &copy; 2020 [Themefisher](https://themefisher.com) All Rights
      Reserved
    languageCode: en-us
    languageName: En
    menu:
      footer:
        - URL: about
          name: About
          weight: 1
        - URL: project
          name: Project
          weight: 2
        - URL: service
          name: Service
          weight: 3
        - URL: pricing
          name: Pricing
          weight: 4
        - URL: faq
          name: FAQ
          weight: 5
        - URL: contact
          name: Contact
          weight: 6
      main:
        - URL: /
          name: Home
          weight: 1
        - URL: about
          name: About
          weight: 2
        - URL: project
          name: Project
          weight: 3
        - URL: blog
          name: Blog
          weight: 4
        - hasChildren: yes
          name: Pages
          weight: 5
        - URL: faq
          name: FAQ
          parent: Pages
        - URL: pricing
          name: Pricing
          parent: Pages
        - URL: service
          name: Service
          parent: Pages
        - URL: contact
          name: Contact
          weight: 6
    weight: 2
